---
- name: Hello Events 100
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 100
        delay: 1
  rules:
    - name: Say Hello
      condition: true
      action:
        debug:
...
