---
- name: k8s-route-event
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Route
  rules:
    - name: "Control Route"
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: hello
          organization: Default
          retries: 1
          delay: 10
...
